import { useEffect, useMemo, useState } from "react";
import { localCoder } from "./engine";
type FileItem={name:string;language:string;content:string}; type Message={role:"user"|"assistant";text:string;mode:"online"|"offline"};
const starter:FileItem[]=[
{name:"src/main.py",language:"python",content:'def hello(name):\n    return f"Hello, {name}!"\n\nprint(hello("Developer"))\n'},
{name:"README.md",language:"markdown",content:"# Nexus Code\n\nA personal AI coding workspace.\n"},
{name:"package.json",language:"json",content:'{\n  "name":"my-project",\n  "version":"1.0.0"\n}\n'}];
export default function App(){
 const[online,setOnline]=useState(navigator.onLine),[files,setFiles]=useState<FileItem[]>(starter),[active,setActive]=useState("src/main.py"),[input,setInput]=useState(""),[messages,setMessages]=useState<Message[]>([]),[busy,setBusy]=useState(false),[api,setApi]=useState(localStorage.getItem("nexus_api")||"");
 useEffect(()=>{const f=()=>setOnline(navigator.onLine);addEventListener("online",f);addEventListener("offline",f);return()=>{removeEventListener("online",f);removeEventListener("offline",f)}},[]);
 useEffect(()=>localStorage.setItem("nexus_api",api),[api]);
 const current=useMemo(()=>files.find(f=>f.name===active)||files[0],[files,active]);
 const updateFile=(content:string)=>setFiles(fs=>fs.map(f=>f.name===active?{...f,content}:f));
 async function ask(){const prompt=input.trim();if(!prompt||busy)return;setInput("");setMessages(m=>[...m,{role:"user",text:prompt,mode:online&&api?"online":"offline"}]);setBusy(true);
  try{if(online&&api){const r=await fetch(api.replace(/\/$/,"")+"/api/agent",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt,files})});if(!r.ok)throw new Error();const d=await r.json();if(d.files)setFiles(d.files);setMessages(m=>[...m,{role:"assistant",text:d.message||"Done.",mode:"online"}]);}
  else{const r=localCoder(prompt,current?.content||"");if(r.content)updateFile(r.content);setMessages(m=>[...m,{role:"assistant",text:r.text,mode:"offline"}]);}}
  catch{const r=localCoder(prompt,current?.content||"");if(r.content)updateFile(r.content);setMessages(m=>[...m,{role:"assistant",text:"Online model unavailable. Switched to the local coding engine.\n\n"+r.text,mode:"offline"}]);}finally{setBusy(false)}}
 function newFile(){const name=window.prompt("File name","src/new-file.js");if(!name||files.some(f=>f.name===name))return;setFiles(fs=>[...fs,{name,language:name.split(".").pop()||"text",content:""}]);setActive(name)}
 return <div className="code-app"><header className="topbar"><div className="brand"><div className="brandmark">N</div><div><b>NEXUS CODE</b><span>AI SOFTWARE ENGINEER</span></div></div><div className="top-actions"><span className={"connection "+(online?"on":"")}><i/> {online?"ONLINE":"OFFLINE"}</span><button onClick={()=>setApi(api?"":(window.prompt("Online API URL","https://your-server.onrender.com")||""))}>⚙ Provider</button></div></header>
 <div className="layout"><aside className="files"><div className="section-title">EXPLORER <button onClick={newFile}>＋</button></div><div className="project">▾ NEXUS PROJECT</div>{files.map(f=><button key={f.name} className={"file "+(f.name===active?"active":"")} onClick={()=>setActive(f.name)}><span>{f.language==="python"?"🐍":f.language==="json"?"{}":"◇"}</span>{f.name}</button>)}<div className="agent-card"><strong>AGENT MODE</strong><p>Ask me to create, edit, explain, refactor or debug your project.</p><span>● {online&&api?"Cloud model":"Local engine"}</span></div></aside>
 <section className="editor"><div className="tabs"><div className="tab active">{current?.name||"untitled"} <span>×</span></div><div className="run">▶ Run</div></div><div className="editor-body"><div className="line-numbers">{(current?.content||"").split("\n").map((_,i)=><span key={i}>{i+1}</span>)}</div><textarea value={current?.content||""} onChange={e=>updateFile(e.target.value)} spellCheck={false}/></div><div className="editor-status"><span>Ln 1, Col 1</span><span>{current?.language?.toUpperCase()}</span><span>UTF-8</span><span>Spaces: 4</span></div></section>
 <aside className="agent"><div className="agent-head"><div><b>✦ NEXUS AGENT</b><small>CODING ASSISTANT</small></div><span className={busy?"thinking":""}>{busy?"THINKING…":"READY"}</span></div><div className="chat">{!messages.length&&<div className="welcome"><div className="spark">✦</div><h2>What are we building?</h2><p>Describe the task. Nexus can reason about your files and propose code changes.</p><div className="suggestions">{["Build a REST API for this project","Find and fix bugs in this file","Explain this code simply","Refactor this into clean code"].map(x=><button key={x} onClick={()=>setInput(x)}>{x}</button>)}</div></div>}{messages.map((m,i)=><div className={"message "+m.role} key={i}><small>{m.role==="user"?"YOU":"NEXUS"} · {m.mode}</small><p>{m.text}</p></div>)}</div><div className="prompt"><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();ask()}}} placeholder="Ask Nexus to change your code…"/><button onClick={ask} disabled={busy}>↑</button><small>Enter to send · Shift + Enter for new line</small></div></aside></div></div>}
